- name: Create elasticsearch users
  uri:
    method: PUT
    url: "https://localhost:9200/_xpack/security/user/{{ item.name }}"
    user: "{{ elasticsearch_default_user }}"
    password: "{{ elasticsearch_elastic_pass }}"
    force_basic_auth: yes
    validate_certs: no
    headers:
      Content-Type: "application/json"
    body: '{ "password": "{{ item.password }}", "roles": "{{ item.roles }}" }'
    body_format: json
    return_content: yes
    status_code: 200
  with_items:
    - "{{ elasticsearch_new_users }}"
  no_log: true

- name: Change passwords
  uri:
    method: PUT
    url: "https://localhost:9200/_xpack/security/user/{{ item.name }}/_password"
    user: "{{ elasticsearch_default_user }}"
    password: "{{ elasticsearch_default_pass }}"
    force_basic_auth: yes
    validate_certs: no
    headers:
      Content-Type: "application/json"
    body: '{ "password": "{{ item.password }}" }'
    body_format: json
    return_content: yes
    status_code: 200
  with_items:
    - "{{ elasticsearch_new_users }}"
    - "{{ elasticsearch_xpack_users }}"
  no_log: true
