mongodb_create_dbs:
  - { db: providerload, db_user: provider-rw, db_user_pass: MyPass }
  - { db: memberload, db_user: member-rw, db_user_pass: MyPass }
  - { db: communicationload, db_user: communication-rw, db_user_pass: MyPass }
  - { db: casesload, db_user: cases-rw, db_user_pass: MyPass }
mongo_express:
  - { db: admin, db_user: mongo_express, db_role: readWriteAnyDatabase, db_user_pass: MyPass }
mongodb_admin_user_pass: MyPass
