rabbitmq_erlang_solutions: "https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
rabbitmq_repo: "deb http://www.rabbitmq.com/debian/ testing main"
rabbitmq_apt_key: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
rabbitmq_erlang_pkgs:
  - erlang
  - erlang-nox
rabbitmq_env: dev
rabbitmq_tcp_listeners: 5672
rabbitmq_ssl_listeners: 5671
rabbitmq_cert_folder: "/etc/rabbitmq/ssl"
rabbitmq_certs:
  - "files/certs/{{ rabbitmq_env }}/aim-trust-chain.p7b"
  - "files/certs/{{ rabbitmq_env }}/rabbit-mq-{{ rabbitmq_env }}.crt"
  - "files/certs/{{ rabbitmq_env }}/rabbitmq-{{ rabbitmq_env }}-private.key"
rabbitmq_ca_cert: "{{ rabbitmq_cert_folder }}/aim-trust-chain.p7b"
rabbitmq_certfile: "{{ rabbitmq_cert_folder }}/rabbit-mq-{{ rabbitmq_env }}.crt"
rabbitmq_keyfile: "{{ rabbitmq_cert_folder }}/rabbitmq-{{ rabbitmq_env }}-private.key"
rabbitmq_definitions: "/etc/rabbitmq/definitions.json"
rabbitmq_management_port: 15672
rabbitmq_ssl_enabled: false
rabbitmq_config_file: "/etc/rabbitmq/rabbitmq.config"
