elasticsearch_repo_gpg_key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
elasticsearch_gpg_key_id: "46095ACC8548582C1A2699A9D27D666CD88E42B4"
elasticsearch_repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
elasticsearch_repo_filename: "elastic-5.x"
#this is a list with required pkgs
elasticsearch_common_pkgs:
  - apt-transport-https 
  - openjdk-8-jre
#elasticsearch version 5.6.3 required
elasticsearch_pkg_version: "elasticsearch=5.6.3"
elasticsearch_cluster_name: "elasticsearch"
elasticsearch_config_file: "/etc/elasticsearch/elasticsearch.yml"
elasticsearch_xpack: false
elasticsearch_plugin_bin: "/usr/share/elasticsearch/bin/elasticsearch-plugin"
