elasticsearch_repo_gpg_key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
elasticsearch_gpg_key_id: "46095ACC8548582C1A2699A9D27D666CD88E42B4"
elasticsearch_repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
elasticsearch_repo_filename: "elastic-5.x"
#this is a list with required pkgs
elasticsearch_common_pkgs:
  - apt-transport-https 
  - openjdk-8-jre
#elasticsearch version 5.6.3 required
elasticsearch_pkg_version: "elasticsearch=5.6.3"
elasticsearch_cluster_name: "elasticsearch-{{ elasticsearch_env }}"
elasticsearch_config_file: "/etc/elasticsearch/elasticsearch.yml"
elasticsearch_xpack: false
elasticsearch_plugin_bin: "/usr/share/elasticsearch/bin/elasticsearch-plugin"
elasticsearch_xpack_license_url: "https://localhost:9200/_xpack/license"
elasticsearch_user: "elastic"
elasticsearch_pass: "changeme"
elasticsearch_env: "dev"
elasticsearch_ssl_dir: "/etc/elasticsearch/ssl"
elasticsearch_ssl_private_key: "certs/{{ elasticsearch_env }}/elasticsearch.{{ elasticsearch_env }}.xformdevpoc.com.key"
elasticsearch_ssl_cert: "certs/{{ elasticsearch_env }}/elasticsearch.{{ elasticsearch_env }}.xformdevpoc.com.crt"
elasticsearch_ssl_ca: "aimca.crt"
# this should be in vault
elasticsearch_xpack_users:
  - { name: kibana, password: some_new_pass1 }
  - { name: logstash_system, password: some_new_pass2 }
  - { name: elastic, password: some_new_pass3 }
