- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Download consul archive and unzip
  unarchive:
    src: "{{ consul_archive }}"
    dest: "{{ consul_dest }}"
    creates: "{{ consul_dest }}/consul"
    remote_src: yes

- name: Create needed directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0744
  with_items:
    - "{{ consul_pers_storage }}"
    - "{{ consul_config_dir }}"

- name: Bootstrap leader
  template:
    src: bootstrap_config.json.j2
    dest: "{{ consul_config_dir }}/config.json"
  run_once: true
  delegate_to: "{{ ansible_play_hosts[0] }}"
  notify: Restart Consul

- name: Configure servers
  template:
    src: server_config.json.j2
    dest: "{{ consul_config_dir }}/server.json"
  when: 
    - "ansible_hostname != ansible_play_hosts[0]"
    - "ansible_hostname != consul_client|default (omit)"
  notify: Restart Consul

- name: Configure client
  template:
    src: client_config.json.j2
    dest: "{{ consul_config_dir }}/client.json"
  when: 
    - "consul_client is defined"
    - "ansible_hostname == consul_client"
  notify: Restart Consul

- name: Copy SystemD service 
  template:
    src: consul.service.j2
    dest: /lib/systemd/system/consul.service

- name: Start Consul
  systemd: 
    name: consul
    state: started
    daemon_reload: yes
