- name: Import Elasticsearch repo GPG key
  apt_key:
    url: "{{ elasticsearch_repo_gpg_key }}"
    id: "{{ elasticsearch_gpg_key_id }}"
    state: present

- name: Add Elasticsearch 5.x repository
  apt_repository:
    repo: "{{ elasticsearch_repo }}"
    state: present
    filename: "{{ elasticsearch_repo_filename }}"

- name: Install Elasticsearch common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ elasticsearch_common_pkgs }}"

- name: Install "{{ elasticsearch_pkg_version }}" version
  apt:
    name: "{{ elasticsearch_pkg_version }}"
    state: present
  notify: Restart Elasticsearch

- name: Copy elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_config_file }}"
  notify: Restart Elasticsearch
