- name: Reset built-in user passwords
  uri:
    method: PUT
    url: "https://localhost:9200/_xpack/security/user/{{ item.name }}/_password"
    user: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_pass }}"
    force_basic_auth: yes
    validate_certs: no
    headers:
      Content-Type: "application/json"
    body: '{ "password": "{{ item.password }}" }'
    body_format: json
    return_content: yes
    status_code: 200
  with_items:
    - "{{ elasticsearch_xpack_users }}"
  no_log: true
