- name: Create directory for ssl certificates
  file:
    path: "{{ elasticsearch_ssl_dir }}"
    mode: 0755
    state: directory

- name: Copy ssl certificates
  copy:
    src: "{{ item }}"
    dest: "{{ elasticsearch_ssl_dir }}/{{ item.split('/')[-1] }}"
    owner: elasticsearch
    group: elasticsearch
    mode: 0400
  notify: Restart Elasticsearch
  with_items:
    - "{{ elasticsearch_ssl_private_key }}"
    - "{{ elasticsearch_ssl_cert }}"
    - "{{ elasticsearch_ssl_ca }}"

- name: Copy cert to /usr/local/share/ca-certificates
  copy:
    src: "{{ elasticsearch_ssl_dir }}/{{ elasticsearch_ssl_ca }}"
    dest: /usr/local/share/ca-certificates
    remote_src: yes
  register: cert

- name: Install CA
  shell: update-ca-certificates
  register: install_ca
  changed_when: 'install_ca is succeeded'
  when: 'cert is changed '

- name: Install xpack plugin
  elasticsearch_plugin:
    name: x-pack
    plugin_bin: "{{ elasticsearch_plugin_bin }}"
    state: present
  register: xpack_install
  notify: Restart Elasticsearch

- name: Restart Elasticsearch if xpack was installed
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
  when: 'xpack_install is changed'
  register: restart_elasticsearch

- name: Need time for xpack to be enabled 
  wait_for:
    timeout: 120 
  when: 'xpack_install is changed'

- name: Check if x-pack has license
  uri:
    method: GET
    url: "{{ elasticsearch_xpack_license_url }}"
    user: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_pass }}"
    return_content: yes
    validate_certs: no
  register: elasticsearch_license_activated

- name: Print current license
  debug:
    var: elasticsearch_license_activated

- name: Activate Xpack license
  uri:
    method: PUT
    url: "{{ elasticsearch_xpack_license_url }}?acknowledge=true"
    user: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_pass }}"
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('file','xpack.json') }}"
    return_content: yes
    validate_certs: no
  register: xpack_activated 
  #  changed_when: "xpack_activated.status == 200"
  changed_when: "xpack_activated.json.acknowledged == true"
  when: >
    elasticsearch_license_activated.json.license.status != 'valid' and 
    elasticsearch_license_activated.json.license.type == 'trial'

- name: Check new license
  uri:
    method: GET
    url: "{{ elasticsearch_xpack_license_url }}"
    user: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_pass }}"
    return_content: yes
    validate_certs: no
  when: >
    elasticsearch_license_activated.json.license.status != 'valid' and 
    elasticsearch_license_activated.json.license.type == 'trial'

