- name: Install python-pip
  apt:
    name: python-pip

- name: Install docker-py
  pip:
    name: docker-py

- name: Start zabbix-agent container
  docker_container:
    name: zabbix-agent
    image: "{{ zabbix_agent_docker_image }}"
    published_ports:
      - 10050
    volumes:
      - /proc:/coreos/proc
      - /sys:/coreos/sys
      - /dev:/coreos/dev
      - /var/run/docker.sock:/coreos/var/run/docker.sock
      - /etc/zabbix:/etc/zabbix:ro
      - /var/log/zabbix-agent:/var/log/zabbix-agent
      - /usr/bin/iostat:/usr/bin/iostat:ro
    network_mode: host
    command:
      - "{{ ansible_hostname }}"
      - "{{ zabbix_agent_server }}"
