#- name: Create self signed certificates
#  import_role:
#    name: self-signed-certs
#  when: rabbitmq_ssl_enabled|bool == true

- name: Create folder for certificates
  file:
    state: directory
    path: "{{ rabbitmq_cert_folder }}"
    mode: 0755
    owner: root
    group: root

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: "{{ rabbitmq_cert_folder }}"
  with_items: "{{ rabbitmq_certs }}"
  notify: Restart rabbitmq-server

- name: Copy definitions.json
  copy:
    src: definitions.{{ rabbitmq_env }}.json
    dest: "{{ rabbitmq_definitions }}" 
  notify: Restart rabbitmq-server

- name: Copy rabbitmq.config file
  template:
    src: rabbitmq.config.j2
    dest: "{{ rabbitmq_config_file }}" 
  notify: Restart rabbitmq-server

- name: Copy cert to /usr/local/share/ca-certificates 
  copy:
    src: "{{ rabbitmq_certfile }}"
    dest: /usr/local/share/ca-certificates
    remote_src: yes
  register: cert

- name: Install CA
  shell: update-ca-certificates
  register: install_ca
  changed_when: 'install_ca | succeeded'
  when: 'cert | changed '

  #- name: Restart RabbitMQ if there is a change in certs
  #service:
  ##  name: rabbitmq-server
  #  state: restarted
  #  enabled: true
  #  when: >
  #  (((csr is defined) and (csr | changed)) or
  #  ((private_key is defined) and (private_key | changed)) or 
  #  ((selfsigned is defined) and (selfsigned | changed)))
  # these vars are registered in self-signed-certs role
