---
# defaults file for openssl
openssl_dir: "/usr/share/ca-certs"
openssl_domain_prefix: domain.local 
openssl_state: Bulgaria
openssl_locality: Sofia 
openssl_organization: "{{ openssl_domain_prefix }}"
openssl_organizationalunit: IT
openssl_email: "admin@{{ openssl_domain_prefix }}"
openssl_private_key: "{{ openssl_dir }}/privkey.pem"
openssl_csr: "{{ openssl_dir}}/cert-sign-request.csr"
openssl_cert: "{{ openssl_dir }}/fullchain.pem"
openssl_private_key_and_cert: "{{ openssl_dir }}/certs.pem"
