- hosts: 
  - kub1
  - kub2
  - kub3
  remote_user: root
  gather_facts: true
  roles:
  - role: common
  - role: flanneld
    flanneld_etcd_key: "/coreos.com/network"
    flanneld_etcd: "{{ hostvars['kub-master']['ansible_default_ipv4']['address'] }}"
  - role: docker 
    docker_overlay_net: true
  - role: kubernetes
    kubernetes_apiserver_ip: "{{ hostvars['kub-master']['ansible_default_ipv4']['address'] }}"
    kubernetes_master: "http://{{ hostvars['kub-master']['ansible_default_ipv4']['address'] }}:8080"
