- hosts: kub-master
  remote_user: root
  gather_facts: true
  roles:
  - role: common
  - role: etcd
  - role: flanneld
    flanneld_etcd_key: "/coreos.com/network"
  - role: docker 
    docker_overlay_net: true
  - role: kubernetes
    kubernetes_type: master

#  tasks:
#  - name: Dump all vars
#    template:
#      src: dumpall.j2
#      dest: /tmp/ansible.all
