- name: Configure our containers
  hosts: "{{ lxd_container_names }}"
#  - c1
#  - c2
  remote_user: root
  gather_facts: true
  roles:
      #  - role: common
      #  - role: docker-engine
      #  - role: jenkins
    - role: mongodb_create_database
